# Generated by Django 2.1.2 on 2018-11-02 06:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book_info',
            name='book_id',
        ),
        migrations.RemoveField(
            model_name='people_info',
            name='people_id',
        ),
        migrations.AddField(
            model_name='people_info',
            name='book',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='app.Book_info'),
        ),
    ]
