# Generated by Django 2.1.2 on 2018-11-05 03:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20181102_1405'),
    ]

    operations = [
        migrations.AddField(
            model_name='book_info',
            name='publish_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date publish'),
        ),
    ]
